name: changelog_test

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, closed]

jobs:
  changelog_test:
    name: Test changelogs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - id: master
      name: Get modified master changelog files
      uses: Ana06/get-changed-files@v2.2.0
      with:
        filter: '*.changes'
    - name: Test if the master changelog files modified
      run: |
        test -z ${{ steps.master.outputs.all }} || \
        (echo 'Master changelog files cannot be modified directly.' && exit 1)
    - id: changelogs
      name: Get modified changelog files
      uses: Ana06/get-changed-files@v2.2.0
      with:
        filter: '*.changes.*'
    - name: Test if the changelog entries are added
      run: |
        ruby .github/scripts/changelog.rb ${{ steps.changelogs.outputs.added_modified }}

  changelog_approved:
    if: github.event.action != 'closed'
    needs: changelog_test
    runs-on: ubuntu-latest
    steps:
    - name: Changelogs approved
      run : echo "Changelogs approved"

  # warns the user if they merged the PR, but the changelog test failed
  warn_user_if_merged:
    if: always() && github.event.action == 'closed' && github.event.pull_request.merged == true && needs.changelog_test.result == 'failure'
    needs: changelog_test
    runs-on: ubuntu-latest
    steps:
    - name: Remind the author with a comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :warning: The changelog has not been updated. Please update it @${{ github.event.pull_request.user.login }}.
